### ISSUE TITLE
Unable to sync database on SFTP

### ISSUE THREAD

**Issue by B0GDAN** [mitchcapper/KeePassSync#2]
Hello,

Looks like there is a missconfig or a bug somewhere. I created an entry for my sftp server and I get the message Database not online. Unable to sync the databases. Although I'm in debug mode, can't read anything from the prompts, they close immediately. No idea where the logfiles are.

Can you provide some info pls?
Thanks!
Bogdan

**Comment by mitchcapper** [comment]
I am going to close this but feel free to re-open with more detail.   Something you can try is run process monitor and only add a filter for:
![image](https://github.com/mitchcapper/KeePassSync/assets/1643324/36a93f62-d8dd-44a6-a7fc-772cde335656)

and turn off the file/reg/profiling categories just leave the process group open.  

then try to sync.  It should show the SFTP calls and then you can manually try running the same command and see what error it gives.

https://learn.microsoft.com/en-us/sysinternals/downloads/procmon
