### ISSUE TITLE
KeePassSync Flags?

### ISSUE THREAD

**Issue by ghost** [mitchcapper/KeePassSync#3]

**Comment by mitchcapper** [comment]
In general we don't specify who you use for keepass sync, and the idea being it shouldn't matter as the entire database is also encrypted.   I am all for privacy/security detail but I am not sure what this pull request would look like?

**Comment by mitchcapper** [comment]
Sorry but what I mean is keepass sync doesn't really  give the users a list of companies to pick from.    The only drop downs we have are S3 compatible provider (meaning amazon S3 or any of the maybe hundred other S3 compat providers) or SFTP.  With SFTP as well you pick your server we don't give a list.

**Comment by mitchcapper** [comment]
OK you want to add a list of S3 compatible providers along with information about their privacy/security practices.    I assume this would also provide the server urls.  I would recommend a sign up link for users too.   If you are fully implementing this feature then yes I think it would be a benefit to the repo.  If you were only looking to provide the data, another option would be to use that data to generate a markdown readme file with the list and we could direct users there.
